if (GetLocale() == "frFR") then

AtlasLoot_LootTypes = { "Instances - Azeroth", "Instances - Kalimdor", "Instances - Outland", "Rencontres de Raid", "Objets de Sets", "Factions", "JcJ" };

AtlasLoot_Zones = {
    { 
        { "Blackrock Depths", "" },
        { "Blackrock Spire (Lower)", "" },
        { "Blackrock Spire (Upper)", "" },
        { "Blackwing Lair", "" },
        { "The Deadmines", "" },
        { "Gnomeregan", "" },
        { "Molten Core", "" },
        { "Naxxramas", "" },
        { "Scarlet Monestery", "" },
        { "Scholomance", "" },
        { "Shadowfang Keep", "" },
        { "The Stockade", "" },
        { "Stratholme", "" },
        { "The Sunken Temple", "" },
        { "Uldaman", "" },
        { "Zul'Gurub", "" },
    },
    {
        { "Blackfathom Deeps", "" },
        { "Dire Maul (East)", "" },
        { "Dire Maul (North)", "" },
        { "Dire Maul (West)", "" },
        { "Maraudon", "" },
        { "Onyxia's Lair", "" },
        { "Ragefire Chasm", "" },
        { "Razorfen Downs", "" },
        { "Razorfen Kraul", "" },
        { "The Ruins of Ahn'Qiraj", "" },
        { "The Temple of Ahn'Qiraj", "" },
        { "Wailing Caverns", "" },
        { "Zul'Farrak", "" },
    },
    {
        { "CFR: The Slave Pens", "EmptyInstance" },
        { "CFR: The Underbog", "EmptyInstance" },
        { "HC: Ramparts", "EmptyInstance" },
        { "HC: The Blood Furnace", "EmptyInstance" },
    },
    {
        { "Azuregos", "AAzuregos" },
        { "Emeriss", "DEmeriss" },
        { "Kazzak", "KKazzak" },
        { "Lethon", "DLethon"},
        { "Taerar", "DTaerar" },
        { "Ysondre", "DYsondre" },
    },
    {
        { "Objets l\195\169gendaires", "Legendaries" },
        { "Sets JcJ (Niveau 60)", "" },
        { "Sets des Ruines d'Ahn'Qiraj", "" },
        { "Sets du Temple d'Ahn'Qiraj", "" },
        { "Tier 0/0.5", "" },
        { "Tier 1", "" },
        { "Tier 2", "" },
        { "Tier 3", "" },
        { "Sets Zul'Gurub", "" },
    },
    {
        { "L\'Aube d\'Argent", "" },
        { "Rejetons de Nozdormu", "AQBroodRings" },
        { "Cercle C\195\169narien", "" },
        { "Foire de Sombrelune", "Darkmoon" },
        { "Confr\195\169rie du Thorium", "" },
        { "Repaire des Grumegueules", "Timbermaw" },
        { "Tribu Zandalar", "" },
    },
    {
        { "Vall\195\169e d\'Alterac", "" },
        { "Bassin d\'Arathi", "" },
        { "Sets JcJ (Niveau 60)", "" },
        { "Goulet des Warsong", "" },
    },
};

AtlasLoot_Bosses = {
    ["Profondeurs de Brassenoire"] = {
        { "Ghamoo-ra", "BFDGhamoora" },
        { "Dame Sarevess", "BFDLadySarevess" },
        { "Gelihast", "BFDGelihast" },
        { "Baron Aquanis", "BFDBaronAquanis" },
        { "Seigneur Kelris Cr\195\169pusculaire", "BFDTwilightLordKelris" },
        { "Vieux Serra'kis", "BFDOldSerrakis" },
        { "Aku'mai", "BFDAkumai" },
        { "Trash Mobs", "BFDTrash" },
    },
    ["Profondeurs de Blackrock"] = {
        { "Seigneur Roccor", "BRDLordRoccor" },
        { "Grand Interrogateur Gerstahn", "BRDHighInterrogatorGerstahn" },
        { "L\'Ar\195\168ne, Theldren", "BRDArena" },
        { "Houndmaster Grebmar", "BRDHoundmaster" },
        { "Pyromancier Loregrain (rare)", "BRDPyromantLoregrain" },
        { "La chambre forte", "BRDWarderStilgiss" },
        { "Fineous Darkvire", "BRDFineousDarkvire" },
        { "Seigneur Incendius", "BRDLordIncendius" },
        { "Bael'Gar", "BRDBaelGar" },
        { "G\195\169n\195\169ral Angerforge", "BRDGeneralAngerforge" },
        { "Seigneur Golem Argelmach", "BRDGolemLordArgelmach" },
        { "Grim Guzzler", "BRDGuzzler" },
        { "Ambassadeur Cingleflammes", "BRDFlamelash" },
        { "Panzor l\'Invincible (rare)", "BRDPanzor" },
        { "Le Tombeau des Sept", "BRDTomb" },
        { "Magmus", "BRDMagmus" },
        { "Empereur Dagran Thaurissan", "BRDImperatorDagranThaurissan" },
        { "Princesse Moira Bronzebeard", "BRDPrincess" },
        { "Trash Mobs", "BRDTrash" },
    },
    ["Pic Blackrock inf\195\169rieur"] = {
        { "G\195\169n\195\169ralissime Omokk", "LBRSOmokk" },
        { "Seigneur de guerre Spirestone (rare)", "LBRSSpirestoneLord" },
        { "Chasseur d\'ombres Vosh'gajin", "LBRSVosh" },
        { "Maitre de Guerre Voone", "LBRSVoone" },
        { "Mor Grayhoof", "LBRSGrayhoof" },
        { "Matriarche Couveuse", "LBRSSmolderweb" },
        { "Croc Cristalin (rare)", "LBRSCrystalFang" },
        { "Urok Hurleruine", "LBRSDoomhowl" },
        { "Intendant Zigris", "LBRSZigris" },
        { "Gizrul l'Esclavagiste", "LBRSSlavener" },
        { "Halycon", "LBRSHalycon" },
        { "Seigneur Wyrmthalak", "LBRSWyrmthalak" },
        { "Bannok Grimaxe", "LBRSGrimaxe" },
        { "Boucher Spirestone (rare)", "LBRSSpirestoneButcher" },
        { "Trash Mobs", "LBRSTrash" },
    },
    ["Pic Blackrock sup\195\169rieur"] = {
        { "Pyrogarde Proph\195\168te Ardent", "UBRSEmberseer" },
        { "Solakar Voluteflamme", "UBRSSolakar" },
        { "Flamme du p\195\168re", "UBRSFLAME" },
        { "Jed Runewatcher", "UBRSRunewatcher" },
        { "Goraluk Anvilcrack", "UBRSAnvilcrack" },
        { "Rend Blackhand", "UBRSRend" },
        { "Gyth", "UBRSGyth" },
        { "La B\195\170te", "UBRSBeast" },
        { "Seigneur Valthalak", "UBRSValthalak" },
        { "G\195\169n\195\169ral Drakkisath", "UBRSDrakkisath" },
        { "Trash Mobs", "UBRSTrash" },
    },
    ["Repaire de l\'Aile noire"] = {
        { "Tranchetripe l'Indompt\195\169", "BWLRazorgore" },
        { "Vaelastrasz le Corrompu", "BWLVaelastrasz" },
        { "Seigneur des couv\195\169es Lashlayer", "BWLLashlayer" },
        { "Gueule de Feu", "BWLFiremaw" },
        { "Roch\195\169b\195\168ne", "BWLEbonroc" },
        { "Flamegor", "BWLFlamegor" },
        { "Chromaggus", "BWLChromaggus" },
        { "Nefarian", "BWLNefarian" },
        { "Trash Mobs", "BWLTrashMobs" },
    },
    ["Les Mortemines"] = {
        { "Rhahk'Zor", "VCRhahkZor" },
        { "Mineur Johnson (rare)", "VCMinerJohnson" },
        { "Sneed", "VCSneed" },
        { "Gilnid", "VCGilnid" },
        { "Capitaine Vertepeau", "VCCaptainGreenskin" },
        { "Edwin VanCleef", "VCVanCleef" },
        { "Mr. Smite", "VCMrSmite" },
        { "Macaron", "VCCookie" },
        { "Set: Cuir Defias", "VCDefiasSET" },
    },
    ["Hache-Tripes (Est)"] = {
        { "Pusillin", "DMEPusillin" },
        { "Zevrim Thornhoof", "DMEZevrimThornhoof" },
        { "Hydrog\195\169nos", "DMEHydro" },
        { "Lethtendris", "DMELethtendris" },
        { "Alzzin le modeleur", "DMEAlzzin" },
        { "Isalien", "DMEIsalien" },
        { "Trash Mobs", "DMETrash" },
        { "Livre de Hache-Tripes", "DMBooks" },
    },
    ["Hache-Tripes (Nord)"] = {
        { "Garde Mol'dar", "DMNGuardMoldar" },
        { "Kreeg le marteleur", "DMNStomperKreeg" },
        { "Garde Fengus", "DMNGuardFengus" },
        { "Knot Thimblejack", "DMNThimblejack" },
        { "Garde Slip'kik", "DMNGuardSlipkik" },
        { "Captaine Kromcrush", "DMNCaptainKromcrush" },
        { "Roi Gordok", "DMNKingGordok" },
        { "Tribute Run", "DMNTRIBUTERUN" },
        { "Livre de Hache-Tripes", "DMBooks" },
    },
    ["Hache-Tripes (Ouest)"] = {
        { "Tendris Crochebois", "DMWTendrisWarpwood" },
        { "Illyanna Ravenoak", "DMWIllyannaRavenoak" },
        { "Magistrat Kalendris", "DMWMagisterKalendris" },
        { "Tsu'Zee", "DMWTsuzee" },
        { "Immol'thar", "DMWImmolthar" },
        { "Seigneur Hel'nurath", "DMWHelnurath" },
        { "Prince Tortheldrin", "DMWPrinceTortheldrin" },
        { "Trash Mobs", "DMWTrash" },
        { "Livre de Hache-Tripes", "DMBooks" },
    },
    ["Gnomeregan"] = {
        { "Retomb\195\169es Visqueuses", "GnViscousFallout" },
        { "Grubbis", "GnGrubbis" },
        { "Electrocuteur 6000", "GnElectrocutioner6000" },
        { "Mekgineer Thermaplugg", "GnMekgineerThermaplugg" },
        { "Ambassadeur Dark Iron (rare)", "GnDIAmbassador" },
        { "Faucheur de foule 9-60", "GnCrowdPummeler960" },
        { "Trash Mobs", "GnTrash" },
    },
    ["Maraudon"] = {
        { "Noxxion", "MaraNoxxion" },
        { "Tranchefouet", "MaraRazorlash" },
        { "Seigneur Vylelangue", "MaraLordVyletongue" },
        { "Meshlok le collecteur (rare)", "MaraMeshlok" },
        { "Celebras le maudit", "MaraCelebras" },
        { "Glissement de terrain", "MaraLandslide" },
        { "Artisan Gizlock", "MaraTinkererGizlock" },
        { "Rotgrip", "MaraRotgrip" },
        { "Princesse Theradras", "MaraPrincessTheradras" },
    },
    ["C\197\147ur du Magma"] = {
        { "Lucifron", "MCLucifron" },
        { "Magmadar", "MCMagmadar" },
        { "Gehennas", "MCGehennas" },
        { "Garr", "MCGarr" },
        { "Shazzrah", "MCShazzrah" },
        { "Baron Geddon", "MCGeddon" },
        { "Golemagg l\'Incin\195\169rateur", "MCGolemagg" },
        { "Messager de Sulfuron", "MCSulfuron" },
        { "Chambellan Executus", "MCMajordomo" },
        { "Ragnaros", "MCRagnaros" },
        { "Trash Mobs", "MCTrashMobs" },
        { "Drops al\195\169atoire des Boss", "MCRANDOMBOSSDROPPS" },
    },
    ["Naxxramas"] = {
        { "Le Recousu", "NAXPatchwerk" },
        { "Grobbulus", "NAXGrobbulus" },
        { "Gluth", "NAXGluth" },
        { "Thaddius", "NAXThaddius" },
        { "Anub'Rekhan", "NAXAnubRekhan" },
        { "Grande veuve Faerlina", "NAXGrandWidowFaerlina" },
        { "Maexxna", "NAXMaexxna" },
        { "Instructeur Razuvious", "NAXInstructorRazuvious" },
        { "Gothik le Moissonneur", "NAXGothikderHarvester" },
        { "Les quatre Cavaliers", "NAXTheFourHorsemen" },
        { "Noth le Porte-peste", "NAXNothderPlaguebringer" },
        { "Heigan l'Impur", "NAXHeiganderUnclean" },
        { "Loatheb", "NAXLoatheb" },
        { "Sapphiron", "NAXSapphiron" },
        { "Kel'Thuzad", "NAXKelThuzard" },
        { "Trash Mobs", "NAXTrash" },
    },
    ["Repaire d\'Onyxia"] = {
        { "Onyxia", "Onyxia" },
    },
    ["Gouffre de Ragefeu"] = {
        { "Taragaman l\'Affam\195\169", "RFCTaragaman" },
        { "Jergosh l\'Invocateur", "RFCJergosh" },
    },
    ["Souilles de Tranchebauge"] = {
        { "Tuten'kash", "RFDTutenkash" },
        { "Mordresh Oeil de Feu", "RFDMordreshFireEye" },
        { "Glutton", "RFDGlutton" },
        { "Ragglesnout (rare)", "RFDRagglesnout" },
        { "Amnennar le Porte-Froid", "RFDAmnennar" },
        { "Trash Mobs", "RFDTrash" },
    },
    ["Kraal de Tranchebauge"] = {
        { "M\195\169dium Jargba", "RFKDeathSpeakerJargba" },
        { "Seigneur Brusquebroche", "RFKOverlordRamtusk" },
        { "Agathelos l\'Enrag\195\169", "RFKAgathelos" },
        { "Chasseur Aveugle (rare)", "RFKBlindHunter" },
        { "Charlga Trancheflanc", "RFKCharlgaRazorflank" },
        { "Implorateur de la terre Halmgar (rare)", "RFKEarthcallerHalmgar" },
        { "Trash Mobs", "RFKTrash" },
    },
    ["Ruines d'Ahn'Qiraj"] = {
        { "Kurinnaxx", "AQ20Kurinnaxx" },
        { "G\195\169n\195\169ral de division Andorov", "AQ20Andorov" },
        { "Capitaines de Rajaxx", "AQ20CAPTIAN" },
        { "G\195\169n\195\169ral Rajaxx", "AQ20Rajaxx" },
        { "Moam", "AQ20Moam" },
        { "Buru Grandgosier", "AQ20Buru" },
        { "Ayamiss le chasseur", "AQ20Ayamiss" },
        { "Ossirian l'Intouch\195\169", "AQ20Ossirian" },
        { "Livres de classe", "AQ20ClassBooks" },
        { "Enchantements", "AQEnchants" },
    },
    ["Monast\195\168re \195\169carlate"] = {
        { "Maitre-Chien Loksey", "SMHoundmasterLoksey" },
        { "Arcaniste Doan", "SMDoan" },
        { "Herod", "SMHerod" },
        { "Grand Inquisiteur Fairbanks", "SMFairbanks" },
        { "Commandant Mograine", "SMMograine" },
        { "Grand Inquisiteur Whitemane", "SMWhitemane" },
        { "Ironspine (rare)", "SMIronspine" },
        { "Azshir le Sans-sommeil (rare)", "SMAzshir" },
        { "Champion Mort (rare)", "SMFallenChampion" },
        { "Mage de Sang Thalnos", "SMBloodmageThalnos" },
        { "Trash Mobs", "SMTrash" },
        { "Set: Cotte de mailles de la croisade \195\169carlate", "SMScarletSET" },
    },
    ["Scholomance"] = {
        { "R\195\169gisseur sanglant de Kirtonos",  "SCHOLOBloodSteward" },
        { "Kirtonos le H\195\169rault", "SCHOLOKirtonostheHerald" },
        { "Jandice Barov", "SCHOLOJandiceBarov" },
        { "Cliquetripes", "SCHOLORattlegore" },
        { "Chevalier de la mort Darkreaver", "SCHOLODeathKnight" },
        { "Marduk Noir\195\169tang", "SCHOLOMarduk" },
        { "Vectus", "SCHOLOVectus" },
        { "Ras Murmegivre", "SCHOLORasFrostwhisper" },
        { "Kormok", "SCHOLOKormok" },
        { "Instructeur Malicia", "SCHOLOInstructorMalicia" },
        { "Docteur Theolen Krastinov", "SCHOLODoctorTheolenKrastinov" },
        { "Gardien du Savoir Polkelt", "SCHOLOLorekeeperPolkelt" },
        { "Le Voracien", "SCHOLOTheRavenian" },
        { "Seigneur Alexei Barov", "SCHOLOLordAlexeiBarov" },
        { "Dame Illucia Barov", "SCHOLOLadyIlluciaBarov" },
        { "Sombre Maitre Gandling", "SCHOLODarkmasterGandling" },
        { "Trash Mobs", "SCHOLOTrash" },
    },
    ["Donjon d\'Ombrecroc"] = {
        { "Razorclaw le Boucher", "BSFRazorclawtheButcher" },
        { "Baron Silverlaine", "BSFSilverlaine" },
        { "Commandant Springvale", "BSFSpringvale" },
        { "Odo l'Aveugle", "BSFOdotheBlindwatcher" },
        { "Fenrus le D\195\169voreur", "BSFFenrustheDevourer" },
        { "Maître-loup Nandos", "BSFWolfMasterNandos" },
        { "Archimage Arugal", "BSFArchmageArugal" },
        { "Trash Mobs", "BSFTrash" },
    },
    ["La Prison"] = {
        { "Kam Deepfury", "SWStKamDeepfury" },
        { "Bruegal Ironknuckle", "SWStBruegalIronknuckle" },
    },
    ["Stratholme"] = {
        { "Skul", "STRATSkull" },
        { "Stratholme Courier", "STRATStratholmeCourier" },
        { "Fras Siabi", "STRATFrasSiabi" },
        { "Hearthsinger Forresten", "STRATHearthsingerForresten" },
        { "Le Condamn\195\169", "STRATTheUnforgiven" },
        { "Timmy le Cruel", "STRATTimmytheCruel" },
        { "Maitre Cannonier Willey", "STRATCannonMasterWilley" },
        { "Archiviste Galford", "STRATArchivistGalford" },
        { "Balnazzar", "STRATBalnazzar" },
        { "Sothos et Jarien", "STRATSothosJarien" },
        { "Stonespine", "STRATStonespine" },
        { "Barone Anastari", "STRATBaronessAnastari" },
        { "Nerub'enkan", "STRATNerubenkan" },
        { "Maleki le Blafard", "STRATMalekithePallid" },
        { "Magistrat Barthilas", "STRATMagistrateBarthilas" },
        { "Ramstein Grandgosier", "STRATRamsteintheGorger" },
        { "Baron Rivendare", "STRATBaronRivendare" },
        { "Trash Mobs", "STRATTrash" },
    },
    ["Le temple englouti"] = {
        { "Troll Miniboss", "STTrollMinibosses" },
        { "Atal'alarion", "STAtalalarion" },
        { "Fauche-r\195\170ve", "STDreamscythe" },
        { "Tisserand", "STWeaver"},
        { "Avatar d\'Hakkar", "STAvatarofHakkar" },
        { "Jammal'an le Proph\195\168te", "STJammalan" },
        { "Ogom le Corrompu", "STOgom" },
        { "Morphaz", "STMorphaz" },
        { "Hazzas", "STHazzas" },
        { "Ombre d\'Eranikus", "STEranikus" },
        { "Trash Mobs", "STTrash" },
    },
    ["Le temple d\'Ahn\'Qiraj"] = {
        { "Proph\195\168te Skeram", "AQ40Skeram" },
        { "La famille Insecte", "AQ40Vem" },
        { "Garde de guerre Sartura", "AQ40Sartura" },
        { "Fankriss l'Inflexible", "AQ40Fankriss" },
        { "Viscidus", "AQ40Viscidus" },
        { "Princesse Huhuran", "AQ40Huhuran" },
        { "Les Empereurs Jumeaux", "AQ40Emperors" },
        { "Ouro", "AQ40Ouro" },
        { "C'Thun", "AQ40CThun" },
        { "Trash Mobs", "AQ40Trash" },
        { "Enchantements", "AQEnchants" },
        { "Event de l'ouverture d\'AQ", "AQOpening" },
    },
    ["Uldaman"] = {
        { "Revelosh", "UldRevelosh" },
        { "Ironaya", "UldIronaya" },
        { "Garde en pierre Antique", "UldAncientStoneKeeper" },
        { "Galgann Firehammer", "UldGalgannFirehammer" },
        { "Grimlok", "UldGrimlok" },
        { "Archaedas", "UldArchaedas" },
        { "Trash Mobs", "UldTrash" },
    },
    ["Cavernes des lamentations"] = {
        { "Seigneur Cobrahn", "WCLordCobrahn" },
        { "Dame Anacondra", "WCLadyAnacondra" },
        { "Kresh", "WCKresh" },
        { "Seigneur Pythas", "WCLordPythas" },
        { "Skum", "WCSkum" },
        { "Seigneur Serpentis", "WCLordSerpentis" },
        { "Verdan l'Immortel", "WCVerdan" },
        { "Mutanus le D\195\169voreur", "WCMutanus" },
        { "Dragon f\195\169\195\169rique D\195\169vian", "WCDeviateFaerieDragon" },
        { "Set: Etreinte de la vip\195\168re", "WCViperSET" },
    },
    ["Zul'Farrak"] = {
        { "Antu'sul", "ZFAntusul" },
        { "Sorcier-docteur Zum'rah", "ZFWitchDoctorZumrah" },
        { "Pr\195\170tre des ombres Sezz'ziz", "ZFSezzziz" },
        { "Gahz'rilla", "ZFGahzrilla" },
        { "Dustwraith", "ZFDustwraith" },
        { "Ukorz Scalpessable", "ZFChiefUkorzSandscalp" },
        { "Zerillis", "ZFZerillis" },
        { "Trash Mobs", "ZFTrash" },
    },
    ["Zul'Gurub"] = {
        { "Grande Pr\195\170tresse Jeklik", "ZGJeklik" },
        { "Grand Pr\195\170tre Venoxis", "ZGVenoxis" },
        { "Grande Pr\195\170tresse Mar'li", "ZGMarli" },
        { "Seigneur sanglant Mandokir", "ZGMandokir" },
        { "Gri'lek du Sang de fer", "ZGGrilek" },
        { "Hazza'rah Tisser\195\170ve", "ZGHazzarah" },
        { "Renataki des Mille lames", "ZGRenataki" },
        { "Wushoolay la Sorci\195\168re des temp\195\170tes", "ZGWushoolay" },
        { "Gahz'ranka", "ZGGahzranka" },
        { "Grand Pr\195\170tre Thekal", "ZGThekal" },
        { "Grande Pr\195\170tresse Arlokk", "ZGArlokk" },
        { "Jin'do le mal\195\169ficieur", "ZGJindo" },
        { "Hakkar", "ZGHakkar" },
        { "Butin Al\195\169atoire des Boss", "ZGShared" },
        { "Trash Mobs", "ZGTrash" },
        { "Enchantements", "ZGEnchants" },
    },
    ["Sets JcJ (Niveau 60)"] = {
        { "Druide", "PVPDruid" },
        { "Chasseur", "PVPHunter" },
        { "Mage", "PVPMage" },
        { "Paladin", "PVPPaladin" },
        { "Pr\195\170tre", "PVPPriest" },
        { "Voleur", "PVPRogue" },
        { "Chaman", "PVPShaman" },
        { "D\195\169moniste", "PVPWarlock" },
        { "Guerrier", "PVPWarrior" },
        { "Armes 1", "PVPWeapons1" },
        { "Armes 2", "PVPWeapons2" },
    },
    ["Sets des Ruines d'Ahn'Qiraj"] = {
        { "Druide", "AQ20Druid" },
        { "Chasseur", "AQ20Hunter" },
        { "Mage", "AQ20Mage" },
        { "Paladin", "AQ20Paladin" },
        { "Pr\195\170tre", "AQ20Priest" },
        { "Voleur", "AQ20Rogue" },
        { "Chaman", "AQ20Shaman" },
        { "D\195\169moniste", "AQ20Warlock" },
        { "Guerrier", "AQ20Warrior" },
    },
    ["Sets du Temple d'Ahn'Qiraj"] = {
        { "Druide", "AQ40Druid" },
        { "Chasseur", "AQ40Hunter" },
        { "Mage", "AQ40Mage" },
        { "Paladin", "AQ40Paladin" },
        { "Pr\195\170tre", "AQ40Priest" },
        { "Voleur", "AQ40Rogue" },
        { "Chaman", "AQ40Shaman" },
        { "D\195\169moniste", "AQ40Warlock" },
        { "Guerrier", "AQ40Warrior" },
    },
    ["Sets Zul'Gurub"] = {
        { "Druide", "ZGDruid" },
        { "Chasseur", "ZGHunter" },
        { "Mage", "ZGMage" },
        { "Paladin", "ZGPaladin" },
        { "Pr\195\170tre", "ZGPriest" },
        { "Voleur", "ZGRogue" },
        { "Chaman", "ZGShaman" },
        { "D\195\169moniste", "ZGWarlock" },
        { "Guerrier", "ZGWarrior" },
    },
    ["Tier 0/0.5"] = {
        { "Druide", "T0Druid" },
        { "Chasseur", "T0Hunter" },
        { "Mage", "T0Mage" },
        { "Paladin", "T0Paladin" },
        { "Pr\195\170tre", "T0Priest" },
        { "Voleur", "T0Rogue" },
        { "Chaman", "T0Shaman" },
        { "D\195\169moniste", "T0Warlock" },
        { "Guerrier", "T0Warrior" },
    },
    ["Tier 1"] = {
        { "Druide", "T1Druid" },
        { "Chasseur", "T1Hunter" },
        { "Mage", "T1Mage" },
        { "Paladin", "T1Paladin" },
        { "Pr\195\170tre", "T1Priest" },
        { "Voleur", "T1Rogue" },
        { "Chaman", "T1Shaman" },
        { "D\195\169moniste", "T1Warlock" },
        { "Guerrier", "T1Warrior" },
    },
    ["Tier 2"] = {
        { "Druide", "T2Druid" },
        { "Chasseur", "T2Hunter" },
        { "Mage", "T2Mage" },
        { "Paladin", "T2Paladin" },
        { "Pr\195\170tre", "T2Priest" },
        { "Voleur", "T2Rogue" },
        { "Chaman", "T2Shaman" },
        { "D\195\169moniste", "T2Warlock" },
        { "Guerrier", "T2Warrior" },
    },
    ["Tier 3"] = {
        { "Druide", "T3Druid" },
        { "Chasseur", "T3Hunter" },
        { "Mage", "T3Mage" },
        { "Paladin", "T3Paladin" },
        { "Pr\195\170tre", "T3Priest" },
        { "Voleur", "T3Rogue" },
        { "Chaman", "T3Shaman" },
        { "D\195\169moniste", "T3Warlock" },
        { "Guerrier", "T3Warrior" },
    },
    ["L\'Aube d\'Argent"] = {
        { "Insignes Aube-Croisade", "Argent1" },
        { "Amical/Honor\195\169", "Argent2" },
        { "R\195\169v\195\169r\195\169/Exalt\195\169", "Argent3" },
    },
    ["Cercle C\196\169narien"] = {
        { "Amical", "Cenarion1" },
        { "Honor\195\169", "Cenarion2" },
        { "R\195\169v\195\169r\195\169", "Cenarion3" },
        { "Exalt\195\169", "Cenarion4" },
    },
    ["Confr\196\169rie du Thorium"] = {
        { "Amical", "Thorium1" },
        { "Honor\195\169", "Thorium2" },
        { "R\195\169v\195\169r\195\169", "Thorium3" },
        { "Exalt\195\169", "Thorium4" },
    },
    ["Tribu Zandalar"] = {
        { "Amical", "Zandalar1" },
        { "Honor\195\169", "Zandalar2" },
        { "R\195\169v\195\169r\195\169", "Zandalar3" },
        { "Exalt\195\169", "Zandalar4" },
    },
    ["Vall\195\169e d\'Alterac"] = {
        { "Amical", "AVFriendly" },
        { "Honor\195\169", "AVHonored" },
        { "R\195\169v\195\169r\195\169", "AVRevered" },
        { "Exalt\195\169", "AVExalted" },
    },
    ["Bassin d\'Arathi"] = {
        { "Amical (Niveau 60)", "ABFriendly" },
        { "Honor\195\169 (Niveau 60)", "ABHonored" },
        { "Honor\195\169  (Niveau 60)", "ABRevered" },
        { "Exalt\195\169  (Niveau 60)", "ABExalted" },
    },
    ["Goulet des Warsong"] = {
        { "Amical (Niveau 60)", "WSGFriendly" },
        { "Honor\195\169 (Niveau 60)", "WSGHonored" },
        { "Honor\195\169  (Niveau 60)", "WSGRevered" },
        { "Exalt\195\169  (Niveau 60)", "WSGExalted" },
    },
};

end
